baseURL: "https://horiaguias.github.io/" 
title: Horia Guias
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 5

params:
    description: "Welcome! I am a Job Market Candidate from Universitat Pompeu Fabra. I am a Behavioral and Experimental Economist working on topics related to perceived responsibility and how it affects economic decision-making."
    author: Horia Guias
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, papers, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Horia Guias
          subtitle: "Welcome! I am a Job Market Candidate from Universitat Pompeu Fabra. I am a Behavioral and Experimental Economist working on topics related to perceived responsibility and how it affects economic decision-making."
          imageUrl: picture.jpeg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:user@gmail.com
        - name: Zoom
          url: https://www.zoom.us/my/user
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=user
        - name: GitHub
          url: https://github.com/user
        - name: YouTube
          url: https://www.youtube.com/@user
        - name: Substack
          url: https://user.substack.com
        - name: Twitter
          url: https://x.com/user
        - name: Bluesky
          url: https://bsky.app/profile/user.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Horia Guias
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
